--Q1 what is total revvenue generated by male vs female customers
select * from customer;
select sum(purchase_amount) as total_revenue,gender
from customer 
group by gender
--which customer used a discount but still spent more than the average purchase amount
select customer_id , purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount)from customer)
--which are top 5 product which has the highesst average review rating
select item_purchased,round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer 
group by item_purchased
order by avg(review_rating)desc
limit 5;
select * from customer
--compare the average purchase amount b/w standard and express shipping
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

select subscription_status,
count(customer_id)as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(sum(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc
 --Q6 which 5 product have the highest percentage of purchase with discount applied
select item_purchased,
round(100*sum(case when discount_applied='Yes' Then 1 Else 0 END)/count(*),2)as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5
--Q7 Segment customerss into new , returning and loyal based on there total number of previous purchases and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
case when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
End as customer_segment
from customer
)
select customer_segment,count(*) as "Number of customer"
from customer_type
group by customer_segment;
--Q8 what are the top 3 most purchased product within each category
with item_count as(
select category,item_purchased , count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id)desc)as item_rank
from customer
group by category,item_purchased
)
select item_rank,item_purchased,total_orders
from item_count
where item_rank<=3;
--Q9 Are customer who are repeat buyers (more than 5 previous purchases) also likely to be subscriber?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by  subscription_status
--Q10 What is the revenue contribution of each age group
select age_group,sum(purchase_amount) as revenue_contri
from customer
group by age_group
order by revenue_contri desc



